name: Comet-Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    name: Run MSBuild

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Install boost
      uses: MarkusJx/install-boost@v1.0.1
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here: 
        # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
        boost_version: 1.73.0
        # OPTIONAL: Specify a toolset on windows
        # toolset: msvc14.2
        # OPTIONAL: Specify a custon install location
        # boost_install_dir: C:\some_directory
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        windows: |
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
    - name: Run MSBuild
      id: run_msbuild
      working-directory: $
      run: msbuild .\comet-ms\Comet.sln
